[world]
description = "World factory world."
name = "world_factory"
seed = "wfactory_2"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "0x5081bf3216bc7ad4e01d553b7ee32e2fd8972ed154b5d1adf392ddc357139b6"
keystore_path = "~/.snaccounts/oz-sepolia.key"
world_address = "0x01d492807baa08400c3c76b827a19376292bae7f52220539184e2cb339cf268d"
world_block = 2699650

[namespace]
default = "wf"

[writers]
"wf" = ["wf-factory"]
